---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops-apps
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops-apps
  namespace: gitops-apps
spec:
  type: Git
  pathname: https://github.com/fazifs/argocd-rhacm.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: aws-clusters
  namespace: gitops-apps
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
       cluster.open-cluster-management.io/placement: aws-clusters
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: gitops-apps
  namespace: gitops-apps
  labels:
    app: gitops-apps
  annotations:
    apps.open-cluster-management.io/github-path: mariadb-resources
spec:
  channel: gitops-apps/gitops-apps
  placement:
    placementRef:
      kind: PlacementRule
      name: aws-clusters
