# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: gitops-apps

generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - namespace.yaml
  - channel.yaml
  - subscription.yaml
